# Bug added
name: "Assign label and codeowner"
on:
  issues:
    types: [opened]
jobs:
  automate-bug:
    name: Add label to bug and assign the issue
    if: contains(github.event.issue.title, 'bug')
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bug
