name: "Issue updated"
on:
  issues:
#     types: [opened, labeled]
    types: [edited]

jobs:
  issue-edited:
    name: issue edited
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Check
        shell: bash
        run : echo "Issue title ${{ github.event.issue.body }}"
      - name : Get codeowner
        id : codeowner
        shell: bash
        run : |
          ls
          codeowner=$(cut -d' ' -f1 ./bug-owner.txt)
          echo "::set-output name=codeowner::$codeowner"
      
